[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator = "6ZD53Cnb1k646CSP9zZDoooi7cjG4hoAFMQpnha7CWeG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/natalieyeo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
